Repository Open-EO/FuseTS, pull requests merged in 2024-01, with the labels that each got.

#116 Load SAFE format product into a xarray Data Cube
  notebooks/JPEG 2000.ipynb
Labels: prio:high

#110 SRD-05 Multi-temporal outlier filter
  src/fusets/temporal_outliers.py
  tests/conftest.py
  tests/test_temporal_outliers.py
Labels: enhancement, prio:high

#108 SRD-09 document temporal averaging
  docs/source/design.md
  docs/source/images/example_cube.png
Labels: documentation, prio:high
